"""Mapping of the pronunciation symbols to a range of (non-control) ASCII characters."""
from typing import Dict

ASCIICOMPRESSION: Dict[str, str] = {
    "A0"  : "!",
    "A1"  : "#",
    "AH0" : "$",
    "AH1" : "%",
    "AR0" : "&",
    "AR1" : "(",
    "AW0" : ")",
    "AW1" : "*",
    "EE0" : "+",
    "EE1" : ",",
    "IER0": "-",
    "IER1": ".",
    "EH0" : "/",
    "EH1" : "0",
    "EIR0": "1",
    "EIR1": "2",
    "EW0" : "3",
    "EW1" : "4",
    "EWR0": "5",
    "EWR1": "6",
    "EY0" : "7",
    "EY1" : "8",
    "AHY0": "9",
    "AHY1": ":",
    "ə"   : ";",
    "əR"  : "<",
    "IH0" : "=",
    "IH1" : ">",
    "IRE0": "?",
    "IRE1": "@",
    "O0"  : "A",
    "O1"  : "B",
    "OA0" : "C",
    "OA1" : "D",
    "OH0" : "E",
    "OH1" : "F",
    "OIR0": "G",
    "OIR1": "H",
    "OO0" : "I",
    "OO1" : "J",
    "OOR0": "K",
    "OOR1": "L",
    "OR0" : "M",
    "OR1" : "N",
    "OW0" : "O",
    "OW1" : "P",
    "OWR0": "Q",
    "OWR1": "R",
    "OY0" : "S",
    "OY1" : "T",
    "UH0" : "U",
    "UH1" : "V",
    "UR0" : "W",
    "UR1" : "X",
    "U0"  : "Y",
    "U1"  : "Z",
    "B"   : "a",
    "CH"  : "b",
    "D"   : "c",
    "DH"  : "d",
    "F"   : "e",
    "G"   : "f",
    "HH"  : "g",
    "J"   : "h",
    "K"   : "i",
    "L"   : "j",
    "M"   : "k",
    "N"   : "l",
    "NG"  : "m",
    "P"   : "n",
    "RR"  : "o",
    "S"   : "p",
    "SH"  : "q",
    "T"   : "r",
    "TH"  : "s",
    "V"   : "t",
    "W"   : "u",
    "WH"  : "v",
    "Y"   : "w",
    "Z"   : "x",
    "ZH"  : "y",
    "EL"  : "z",
    "EM"  : "{",
    "EN"  : "|",
    "II"  : "}",
    "'"   : "'",
}
