"""Mapping of the pronunciation symbols to a range of (non-control) ASCII characters."""
from typing import Dict

ASCIICOMPRESSION: Dict[str, str] = {
    "A0"  : "!",
    "A1"  : "#",
    "AH0" : "$",
    "AH1" : "%",
    "AR0" : "&",
    "AR1" : "(",
    "AW0" : ")",
    "AW1" : "*",
    "EE0" : "+",
    "EE1" : ",",
    # ""  : "-",
    # ""  : ".",
    # ""  : "/",
    "EH0" : "0",
    "EH1" : "1",
    "ER0" : "2",
    "ER1" : "3",
    "EW0" : "4",
    "EW1" : "5",
    "EY0" : "6",
    "EY1" : "7",
    "AHY0": "8",
    "AHY1": "9",
    # ""  : ":",  # reserved
    # ""  : ";",  # reserved
    # ""  : "<",
    "ə"   : "=",
    # ""  : ">",
    "əR"  : "?",
    "IH0" : "@",
    "IH1" : "A",
    "IR0" : "B",
    "IR1" : "C",
    "O0"  : "D",
    "O1"  : "E",
    "OH0" : "F",
    "OH1" : "G",
    "OO0" : "H",
    "OO1" : "I",
    "OR0" : "J",
    "OR1" : "K",
    "OW0" : "L",
    "OW1" : "M",
    "OY0" : "N",
    "OY1" : "O",
    "UH0" : "P",
    "UH1" : "Q",
    "UR0" : "R",
    "UR1" : "S",
    "U0"  : "T",
    "U1"  : "U",
    "B"   : "V",
    "CH"  : "W",
    "D"   : "X",
    "DH"  : "Y",
    "F"   : "Z",
    "G"   : "a",
    "H"   : "b",
    "J"   : "c",
    "K"   : "d",
    "L"   : "e",
    "M"   : "f",
    "N"   : "g",
    "NG"  : "h",
    "P"   : "i",
    "R"   : "j",
    "S"   : "k",
    "SH"  : "l",
    "T"   : "m",
    "TH"  : "n",
    "V"   : "o",
    "W"   : "p",
    "WH"  : "q",
    "Y"   : "r",
    "Z"   : "s",
    "ZH"  : "t",
    # "EL"  : "u",
    "EM"  : "v",
    "EN"  : "w",
    "II"  : "x",
    "IA0" : "y",
    "IA1" : "z",
    # ""  : "{",
    # ""  : "|",
    # ""  : "}",
    # ""  : "[",
    # ""  : "]",
    # ""  : "^",
    # ""  : "_",
    "'"   : "'",
}
