"""Mapping of the arpabet symbols to a range of (non-control) ASCII characters."""
from typing import Dict

ASCIICOMPRESSION: Dict[str, str] = {
    "AA0": "!",
    "AA1": "#",
    "AE0": "$",
    "AE1": "%",
    "AH0": "&",
    "AH1": "(",
    "AO0": ")",
    "AO1": "*",
    "AR0": "+",
    "AR1": ",",
    "AW0": "-",
    "AW1": ".",
    "AY0": "/",
    "AY1": "0",
    "B": "1",
    "CH": "2",
    "D": "3",
    "DH": "4",
    "EH0": "5",
    "EH1": "6",
    "EL": "7",
    "EM": "8",
    "EN": "9",
    "ER0": ":",
    "ER1": ";",
    "EY0": "<",
    "EY1": "=",
    "F": ">",
    "G": "?",
    "HH": "@",
    "IH0": "A",
    "IH1": "B",
    "II" : "C",
    "IR0": "D",
    "IR1": "E",
    "IW0": "F",
    "IW1": "G",
    "IY0": "H",
    "IY1": "I",
    "JH": "J",
    "K": "K",
    "L": "L",
    "M": "M",
    "N": "N",
    "NG": "O",
    "OH0": "P",
    "OH1": "Q",
    "OO0": "R",
    "OO1": "S",
    "OR0": "T",
    "OR1": "U",
    "OW0": "V",
    "OW1": "W",
    "OY0": "X",
    "OY1": "Y",
    "P": "Z",
    "R": "[",
    "S": "]",
    "SH": "^",
    "T": "_",
    "TH": "`",
    "UH0": "a",
    "UH1": "b",
    "UR0": "c",
    "UR1": "d",
    "UW0": "e",
    "UW1": "f",
    "V": "g",
    "W": "h",
    "WH": "i",
    "Y": "j",
    "YR0": "k",
    "YR1": "l",
    "Z": "m",
    "ZH": "n",
    # "": "o",
    # "": "p",
    # "": "q",
    # "": "r",
    # "": "s",
    # "": "t",
    # "": "u",
    # "": "v",
    # "": "w",
    # "": "x",
    # "": "y",
    # "": "z",
    # "": "~",
    "'": "'",  # apostrophe remains apostrophe
    "AX": "{",
    "AXR": "}",
}
