name: Python package

on:
  pull_request:
    branches:
    - main

jobs:
  validate_dictionary:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'
    - name: Install requirements
      run: poetry install
    - name: Parse dictionary
      working-directory: preprocessing
      run: poetry run python to_json.py
